### ISSUE TITLE
Color Theme and Logo Design

### ISSUE THREAD

**Issue by solliegarcia** [groupsup/groupsup#6]

**Comment by nlaranio** [comment]
Two 500x500px images in my [drive](https://drive.google.com/drive/folders/1_MY1e02h4joU3Y5C5KvvirmwoSE8YAKG?usp=sharing)
they have no backgrounds; there are versions with backgrounds in the discord server

**Comment by nlaranio** [comment]
more in the works but here are the colors
004F2F  primary green
099659 secondary green
9E9E9E  grey
also black and white

**Comment by solliegarcia** [comment]
@nlaranio Have you uploaded the other images you were talking about to the drive?
